<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>ErGe.ControlCenter</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ErGe.Core\ErGe.Core.csproj" />
    <ProjectReference Include="..\ErGe.OwnerControl.Client\ErGe.OwnerControl.Client.csproj" />
  </ItemGroup>
</Project>
